kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: armsrace-dust2-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: armsrace-dust2-1
    spec:
      containers:
      - name: armsrace-dust2-1
        image: registry.npf.dk/npflan/csgo:201910102253
        ports:
        - containerPort: 27015
        - containerPort: 27020
        env:
          - name: SERVER_HOSTNAME
            value: "NPF FFA - CSGO Armsrace 1 - dust2"
          - name: MAP
            value: "de_dust2"
          - name: MAX_PLAYERS
            value: "12"
          - name: TICKRATE
            value: "60"
          - name: GAME_TYPE
            value: "1"
          - name: GAME_MODE
            value: "0"
          - name: TOKEN_API_URL
            valueFrom:
              configMapKeyRef:
                key: url
                name: steam-token-url
        stdin: true
        tty: true
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
        resources:
          requests:
            memory: "4000Mi"
            cpu: "2"
      volumes:
        - name: config-volume
          configMap:
            name: armsrace-dust2
            items:
            - key: server.cfg
              path: server.cfg
---
kind: Service
apiVersion: v1
metadata:
  name: armsrace-dust2-1
  labels:
    app: armsrace-dust2-1
spec:
  selector:
    app: armsrace-dust2-1
  ports:
    - name: gametcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: gameudp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: matchandhltvtcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: matchandhltvudp
      protocol: UDP
      port: 27020
      targetPort: 27020
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: armsrace-dust2
data:
  server.cfg: |
    bot_chatter "off"
    exec autoexec
