kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: armsrace-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: armsrace-1
    spec:
      containers:
      - name: armsrace-1
        image: registry.npf.dk/npflan/csgo:201910102253
        ports:
        - containerPort: 27015
        - containerPort: 27020
        env:
          - name: SERVER_HOSTNAME
            value: "NPF FFA - CSGO Armsrace 1"
          - name: MAP
            value: "ar_baggage"
          - name: MAX_PLAYERS
            value: "12"
          - name: MAPGROUP
            value: "mg_armsrace"
          - name: TICKRATE
            value: "64"
          - name: GAME_TYPE
            value: "1"
          - name: GAME_MODE
            value: "0"
          - name: TOKEN_API_URL
            valueFrom:
              configMapKeyRef:
                key: url
                name: steam-token-url
        stdin: true
        tty: true
        volumeMounts:
        - name: config-volume
          mountPath: /csgo/csgo/cfg/server.cfg
          subPath: server.cfg
          readOnly: true
        - name: config-volume
          mountPath: /csgo/csgo/cfg/gamemode_armsrace.cfg
          subPath: gamemode_armsrace.cfg
          readOnly: true
        - name: config-volume
          mountPath: /csgo/start.sh
          subPath: start.sh
        - name: logs
          mountPath: /logs
        resources:
          requests:
            memory: "4000Mi"
            cpu: "2"


      - name: filebeat
        image: store/elastic/filebeat:7.3.1
        volumeMounts:
        - name: filebeat
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
          readOnly: true

        - name: logs
          mountPath: /logs

        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"

      volumes:
        - name: config-volume
          configMap:
            name: armsrace-1
            defaultMode: 0777
            items:
            - key: server.cfg
              path: server.cfg
            - key: gamemode_armsrace.cfg
              path: gamemode_armsrace.cfg
            - key: start.sh
              path: start.sh
        
        - name: filebeat
          configMap:
            name: filebeat-ffa
            items:
            - key: filebeat.yml
              path: filebeat.yml
        - name: logs
          emptyDir: {}


---
kind: Service
apiVersion: v1
metadata:
  name: armsrace-1
  labels:
    app: armsrace-1
spec:
  selector:
    app: armsrace-1
  ports:
    - name: gametcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: gameudp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: matchandhltvtcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: matchandhltvudp
      protocol: UDP
      port: 27020
      targetPort: 27020
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: armsrace-1
data:
  server.cfg: |
    sv_logsdir /logs
    log on
    exec autoexec
  start.sh: |
    #!/bin/bash
    ## Update game before use
    /steamcmd/steamcmd.sh +login anonymous +force_install_dir /csgo +app_update 740 +quit

    export GAMESERVER_TOKEN=$(curl --silent "$TOKEN_API_URL/token/730/$HOSTNAME")
    export RCON_PASSWORD="$(< /dev/urandom tr -dc A-Za-z0-9 | head -c32; echo)"

    export SERVER_HOSTNAME="${SERVER_HOSTNAME:-}"
    export RCON_PASSWORD="${RCON_PASSWORD:-changeme}"
    export STEAM_ACCOUNT="${GAMESERVER_TOKEN:-changeme}"
    export CSGO_DIR="${CSGO_DIR:-/csgo}"
    export IP="${IP:-0.0.0.0}"
    export PORT="${PORT:-27015}"
    export TICKRATE="${TICKRATE:-64}"
    export GAME_TYPE="${GAME_TYPE:-0}"
    export GAME_MODE="${GAME_MODE:-1}"
    export MAP="${MAP:-de_dust2}"
    export MAPGROUP="${MAPGROUP:-mg_active}"
    export MAXPLAYERS="${MAXPLAYERS:-12}"

    : ${CSGO_DIR:?"ERROR: CSGO_DIR IS NOT SET!"}

    cd $CSGO_DIR

    ### Create dynamic server config
    cat << AUTOEXEC > $CSGO_DIR/csgo/cfg/autoexec.cfg
    hostname "$SERVER_HOSTNAME"
    rcon_password "$RCON_PASSWORD"
    sv_lan 0
    sv_cheats 0
    AUTOEXEC

    ./srcds_run \
        -console \
        -usercon \
        -game csgo \
        -tickrate $TICKRATE \
        -port $PORT \
        -maxplayers_override $MAXPLAYERS \
        +game_type $GAME_TYPE \
        +game_mode $GAME_MODE \
        +mapgroup $MAPGROUP \
        +map $MAP \
        +ip $IP \
        +sv_setsteamaccount $STEAM_ACCOUNT
  gamemode_armsrace.cfg: |
    bot_autodifficulty_threshold_high					0.0	// Value between -20.0 and 20.0 (Amount above avg human contribution score, above which a bot should lower its difficulty)
    bot_autodifficulty_threshold_low					-2.0	// Value between -20.0 and 20.0 (Amount below avg human contribution score, below which a bot should raise its difficulty)
    bot_chatter											off
    bot_defer_to_human_goals							0
    bot_defer_to_human_items							1
    bot_difficulty										1
    bot_quota											10
    bot_quota_mode										fill
    cash_player_bomb_defused							0
    cash_player_bomb_planted							0
    cash_player_damage_hostage							0
    cash_player_interact_with_hostage					0
    cash_player_killed_enemy_default					0
    cash_player_killed_enemy_factor						0
    cash_player_killed_hostage							0
    cash_player_killed_teammate							0
    cash_player_rescued_hostage							0
    cash_team_elimination_bomb_map						0
    cash_team_elimination_hostage_map_t					0
    cash_team_elimination_hostage_map_ct				0
    cash_team_hostage_alive								0
    cash_team_hostage_interaction						0
    cash_team_loser_bonus								0
    cash_team_loser_bonus_consecutive_rounds			0
    cash_team_planted_bomb_but_defused					0
    cash_team_rescued_hostage							0
    cash_team_terrorist_win_bomb						0
    cash_team_win_by_defusing_bomb						0
    cash_team_win_by_hostage_rescue						0
    cash_team_win_by_time_running_out_bomb				0
    cash_team_win_by_time_running_out_hostage			0
    ff_damage_reduction_bullets							0
    ff_damage_reduction_grenade							0
    ff_damage_reduction_grenade_self					0
    ff_damage_reduction_other							0
    mp_afterroundmoney									0
    mp_buytime											0
    mp_buy_anywhere										0
    mp_buy_during_immunity								0
    mp_death_drop_defuser								0	
    mp_death_drop_grenade								0			// 0=none, 1=best, 2=current or best
    mp_death_drop_gun									0			// 0=none, 1=best, 2=current or best
    mp_defuser_allocation								0			// 0=none, 1=random, 2=everyone
    mp_force_pick_time									15
    mp_forcecamera										0			// Set to 1 for team only spectating
    mp_free_armor										2			
    mp_freezetime										6
    mp_friendlyfire										1
    mp_win_panel_display_time							6
    mp_ggprogressive_round_restart_delay			 15
    mp_ggtr_bomb_defuse_bonus							1
    mp_ggtr_bomb_detonation_bonus						1
    mp_ggtr_bomb_pts_for_flash							4
    mp_ggtr_bomb_pts_for_he								3
    mp_ggtr_bomb_pts_for_molotov						5
    mp_ggtr_bomb_pts_for_upgrade						2
    mp_ggtr_bomb_respawn_delay							0
    mp_ggtr_end_round_kill_bonus						1
    mp_ggtr_halftime_delay								0.0
    mp_ggtr_last_weapon_kill_ends_half					0
    mp_respawn_immunitytime								2
    mp_halftime											0
    mp_match_can_clinch									0			// 0=No mercy rule, 1=team can clinch match win early if they win > 1/2 total rounds
    mp_maxmoney											0
    mp_maxrounds										10
    mp_molotovusedelay									0
    mp_playercashawards									0
    mp_roundtime										30
    mp_roundtime_hostage								0
    mp_roundtime_defuse									0
    mp_solid_teammates									0
    mp_startmoney										0
    mp_teamcashawards									0
    mp_timelimit										30
    mp_warmuptime										30
    mp_weapons_allow_zeus								0
    mp_weapons_allow_typecount							-1
    spec_freeze_panel_extended_time						1
    spec_freeze_time									2
    sv_allow_votes										1		// Voting allowed in this mode
    sv_talk_enemy_living								1
    sv_talk_enemy_dead									1		
    sv_arms_race_vote_to_restart_disallowed_after		26
    sv_deadtalk											1
    sv_ignoregrenaderadio								1
    tv_delay											30
    mp_warmup_pausetimer								0
    mp_halftime_pausetimer								0
    mp_randomspawn										1
    mp_randomspawn_los									0
    sv_infinite_ammo									0
    ammo_grenade_limit_flashbang						1
    ammo_grenade_limit_total							3

    //
    mp_weapons_allow_map_placed							0
    mp_weapons_glow_on_ground							0
    mp_display_kill_assists								0
    mp_respawn_on_death_t								1
    mp_respawn_on_death_ct								1
    mp_ct_default_melee									weapon_knife
    mp_ct_default_secondary								""
    mp_ct_default_primary								""
    mp_t_default_melee									weapon_knife
    mp_t_default_secondary								""
    mp_t_default_primary								""

    sv_occlude_players								1
    occlusion_test_async								0

    cl_disablefreezecam 1
    mp_deathcam_skippable 1

