kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: casual-mirage-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: casual-mirage-2
    spec:
      containers:
      - name: casual-mirage-2
        image: npflan/csgo:201810111950
        ports:
        - containerPort: 27015
        - containerPort: 27020
        env:
          - name: SERVER_HOSTNAME
            value: "NPF FFA - CSGO Casual 2 - mirage"
          - name: MAP
            value: "de_mirage"
          - name: MAX_PLAYERS
            value: "12"
          - name: TICKRATE
            value: "60"
          - name: GAME_TYPE
            value: "0"
          - name: GAME_MODE
            value: "0"
          - name: TOKEN_API_URL
            valueFrom:
              configMapKeyRef:
                key: url
                name: steam-token-url
        stdin: true
        tty: true
        resources:
          requests:
            memory: "4000Mi"
            cpu: "2"
---
kind: Service
apiVersion: v1
metadata:
  name: casual-mirage-2
  labels:
    app: casual-mirage-2
spec:
  selector:
    app: casual-mirage-2
  ports:
    - name: gametcp
      protocol: TCP
      port: 27015
      targetPort: 27015
    - name: gameudp
      protocol: UDP
      port: 27015
      targetPort: 27015
    - name: matchandhltvtcp
      protocol: TCP
      port: 27020
      targetPort: 27020
    - name: matchandhltvudp
      protocol: UDP
      port: 27020
      targetPort: 27020
